WRONG_LIST = {
    "Primeira": "1a",
    "Primeiro": "1o",
    "1A": "1a",
    "I GRUPO": "1o grupo",
    "Segunda": "2a",
    "Segundo": "2o",
    "2A": "2a",
    "2 instância": "2a instância",
    "2º grau": "2o grau",
    "II grupo": "2o grupo",
    "Terceira": "3a",
    "Terceiro": "3o",
    "3A": "3a",
    "3º grupo": "3o grupo",
    "III grupo": "3o grupo",
    "Quarta": "4a",
    "Quarto": "4o",
    "IV grupo": "4o grupo",
    "4A": "4a",
    "Quinta": "5a",
    "5A": "5a",
    "Quinto": "5o",
    "Sexta": "6a",
    "Sexto": "6o",
    "6A": "6a",
    "Sétima": "7a",
    "Sétimo": "7o",
    "7A": "7a",
    "Oitava": "8a",
    "Oitavo": "8o",
    "8A": "8a",
    "Nona": "9a",
    "9A": "9a",
    "Nono": "9o",
    "9º grupo": "9o grupo",
    "Décima": "10a",
    "10A": "10a",
    "Décimo": "10o",
    "Décima primeira": "11a",
    "Décimo primeiro": "11o",
    "Décima segunda": "12a",
    "Décimo segundo": "12o",
    "Décima terceira": "13a",
    "Décimo terceiro": "13o",
    "Décima quarta": "14a",
    "Décimo quarto": "14o",
    "Décima quinta": "15a",
    "Décimo quinto": "15o",
    "Décima sexta": "16a",
    "Décimo sexto": "16o",
    "Décima sétima": "17a",
    "Décimo sétimo": "17o",
    "Décima oitava": "18a",
    "Décimo oitavo": "18o",
    "Décima nona": "19a",
    "Décimo nono": "19o",
    "Vigésima": "20a",
    "Vigésimo": "20o",
    "Vigésima primeira": "21a",
    "Vigésimo primeiro": "21o",
    "Vigésima segunda": "22a",
    "Vigésimo segundo": "22o",
    "Vigésima terceira": "23a",
    "Vigésimo terceiro": "23o",
    "Vigésima quarta": "24a",
    "Vigésimo quarto": "24o",
    "Vigésima quinta": "25a",
    "Vigésimo quinto": "25o",
    "Vigésima sétima": "27a",
    "Vigésimo sétimo": "27o",
    "Vigésima oitava": "28a",
}
